module RiversHelper
  def us_states
  [
    [ "Alabama", "al" ],
    [ "Alaska", "ak" ],
    [ "Arizona", "az" ],
    [ "Arkansas", "ar" ],
    [ "California", "ca" ],
    [ "Colorado", "co" ],
    [ "Connecticut", "ct" ],
    [ "Delaware", "de" ],
    [ "Florida", "fl" ],
    [ "Georgia", "ga" ],
    [ "Hawaii", "hi" ],
    [ "Idaho", "id" ],
    [ "Illinois", "il" ],
    [ "Indiana", "in" ],
    [ "Iowa", "ia" ],
    [ "Kansas", "ks" ],
    [ "Kentucky", "ky" ],
    [ "Louisiana", "la" ],
    [ "Maine", "me" ],
    [ "Maryland", "md" ],
    [ "Massachusetts", "ma" ],
    [ "Michigan", "mi" ],
    [ "Minnesota", "mn" ],
    [ "Mississippi", "ms" ],
    [ "Missouri", "mo" ],
    [ "Montana", "mt" ],
    [ "Nebraska", "ne" ],
    [ "Nevada", "nv" ],
    [ "New Hampshire", "nh" ],
    [ "New Jersey", "nj" ],
    [ "New Mexico", "nm" ],
    [ "New York", "ny" ],
    [ "North Carolina", "nc" ],
    [ "North Dakota", "nd" ],
    [ "Ohio", "oh" ],
    [ "Oklahoma", "ok" ],
    [ "Oregon", "or" ],
    [ "Pennsylvania", "pa" ],
    [ "Rhode Island", "ri" ],
    [ "South Carolina", "sc" ],
    [ "South Dakota", "sd" ],
    [ "Tennessee", "tn" ],
    [ "Texas", "tx" ],
    [ "Utah", "ut" ],
    [ "Vermont", "vt" ],
    [ "Virginia", "va" ],
    [ "Washington", "wa" ],
    [ "West Virginia", "wv" ],
    [ "Wisconsin", "wi" ],
    [ "Wyoming", "wy" ]
  ]
  end

  def full_name(state_abrev)
    us_states.select { |state| state[1] == state_abrev }.first.first
  end

  def us_states_hash
  [
    { :name => "Alabama",
        :id => "al" },
    { :name => "Alaska",
        :id => "ak" },
    { :name => "Arizona",
        :id => "az" },
    { :name => "Arkansas",
        :id => "ar" },
    { :name => "California",
        :id => "ca" },
    { :name => "Colorado",
        :id => "co" },
    { :name => "Connecticut",
        :id => "ct" },
    { :name => "Delaware",
        :id => "de" },
    { :name => "Florida",
        :id => "fl" },
    { :name => "Georgia",
        :id => "ga" },
    { :name => "Hawaii",
        :id => "hi" },
    { :name => "Idaho",
        :id => "id" },
    { :name => "Illinois",
        :id => "il" },
    { :name => "Indiana",
        :id => "in" },
    { :name => "Iowa",
        :id => "ia" },
    { :name => "Kansas",
        :id => "ks" },
    { :name => "Kentucky",
        :id => "ky" },
    { :name => "Louisiana",
        :id => "la" },
    { :name => "Maine",
        :id => "me" },
    { :name => "Maryland",
        :id => "md" },
    { :name => "Massachusetts",
        :id => "ma" },
    { :name => "Michigan",
        :id => "mi" },
    { :name => "Minnesota",
        :id => "mn" },
    { :name => "Mississippi",
        :id => "ms" },
    { :name => "Missouri",
        :id => "mo" },
    { :name => "Montana",
        :id => "mt" },
    { :name => "Nebraska",
        :id => "ne" },
    { :name => "Nevada",
        :id => "nv" },
    { :name => "New Hampshire",
        :id => "nh" },
    { :name => "New Jersey",
        :id => "nj" },
    { :name => "New Mexico",
        :id => "nm" },
    { :name => "New York",
        :id => "ny" },
    { :name => "North Carolina",
        :id => "nc" },
    { :name => "North Dakota",
        :id => "nd" },
    { :name => "Ohio",
        :id => "oh" },
    { :name => "Oklahoma",
        :id => "ok" },
    { :name => "Oregon",
        :id => "or" },
    { :name => "Pennsylvania",
        :id => "pa" },
    { :name => "Rhode Island",
        :id => "ri" },
    { :name => "South Carolina",
        :id => "sc" },
    { :name => "South Dakota",
        :id => "sd" },
    { :name => "Tennessee",
        :id => "tn" },
    { :name => "Texas",
        :id => "tx" },
    { :name => "Utah",
        :id => "ut" },
    { :name => "Vermont",
        :id => "vt" },
    { :name => "Virginia",
        :id => "va" },
    { :name => "Washington",
        :id => "wa" },
    { :name => "West Virginia",
        :id => "wv" },
    { :name => "Wisconsin",
        :id => "wi" },
    { :name => "Wyoming",
        :id => "wy" }
    ]
  end


end
